services:
  auth:
    build:
      context: .
    ports:
      - "6080:6080"
    volumes:
      - ../${PROFILE_DIR:-./profile}:/profile
      - ./desktop:/home/abc/Desktop
    environment:
      - PUID
      - PGID
