[supervisord]
nodaemon=true

[program:X11]
command=Xvfb :0 -screen 0 "%(ENV_DISPLAY_WIDTH)s"x"%(ENV_DISPLAY_HEIGHT)s"x24
autorestart=true

[program:x11vnc]
command=/usr/bin/x11vnc -display :0 -forever -shared -loop -xkb -noxrecord -noxfixes -noxdamage -rfbport 5900
autorestart=true
priority=200
depends_on=X11

[program:novnc]
command=/home/alpine/noVNC/utils/novnc_proxy.sh --web vnc_lite.html --file-only
autorestart=true
priority=300
depends_on=x11vnc

[program:fluxbox]
command=fluxbox
autorestart=true
priority=100
depends_on=X11